name: 'Terraform Format with Pull Request update'
description: 'Runs terraform format for a configuration and creates a comment on the GitHub issue'

inputs:
  github-token:
    description: 'The GitHub token for authentication'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      shell: bash

    - name: Post Terraform Format
      if: always()
      uses: redmagnolia/terraform-custom-actions/github-issue-comment@main
      with:
        github-token: ${{ inputs.github-token }}
        format-outcome: ${{ steps.fmt.outcome }}
        format-output: ${{ steps.fmt.outputs.stdout }}
        terraform-step: 'format'
