name: 'GitHub Issue Comment'
description: 'Creates or updates a comment on a GitHub issue for terraform format/init/validate/plan'

inputs:
  github-token:
    description: 'The GitHub Token for authentication on behalf of the workflow'
    required: true
  terraform-step:
    description: 'The terraform step in the workflow'
    required: true
  format-outcome:
    description: 'The status of terraform format'
    required: false
  format-output:
    description: 'The output of terraform format'
    required: false
  init-outcome:
    description: 'The status of terraform init'
    required: false
  init-error:
    description: 'The error of terraform init'
    required: false
  validate-outcome:
    description: 'The status of terraform validate'
    required: false
  validate-error:
    description: 'The error of terraform validate'
    required: false
  valid-plan:
    description: 'The status of the terraform plan'
    required: false
  plan-output:
    description: 'The output of terraform plan'
    required: false
  plan-error:
    description: 'The error of terraform plan'
    required: false

runs:
  using: 'node16'
  main: 'index.js'
