name: 'Terraform Validate with Pull Request update'
description: 'Runs terraform validate for a configuration and creates a comment on the GitHub issue'

inputs:
  github-token:
    description: 'The GitHub token for authentication'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      shell: bash

    - name: Post Terraform Validate
      if: always()
      uses: redmagnolia/terraform-custom-actions/github-issue-comment@v1
      with:
        github-token: ${{ inputs.github-token }}
        validate-outcome: ${{ steps.validate.outcome }}
        validate-error: ${{ steps.validate.outputs.stderr }}
        terraform-step: 'validate'
