name: 'Terraform Plan with Pull Request update'
description: 'Runs terraform plan for a configuration and creates a comment on the GitHub issue'

inputs:
  github-token:
    description: 'The GitHub token for authentication'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.x.x
    
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      shell: bash

    - name: Post Terraform Format
      if: always()
      uses: redmagnolia/terraform-custom-actions/commentator@v1
      with:
        github-token: ${{ inputs.github-token }}
        format-outcome: ${{ steps.fmt.outcome }}
        format-output: ${{ steps.fmt.outputs.stdout }}
        terraform-step: 'format'

    - name: Terraform Init
      id: init
      run: terraform init -no-color
      shell: bash

    - name: Post Terraform Init
      if: always()
      uses: redmagnolia/terraform-custom-actions/commentator@v1
      with:
        github-token: ${{ inputs.github-token }}
        init-outcome: ${{ steps.init.outcome }}
        init-error: ${{ steps.init.outputs.stderr }}
        terraform-step: 'init'

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      shell: bash

    - name: Post Terraform Validate
      if: always()
      uses: redmagnolia/terraform-custom-actions/commentator@v1
      with:
        github-token: ${{ inputs.github-token }}
        validate-outcome: ${{ steps.validate.outcome }}
        validate-error: ${{ steps.validate.outputs.stderr }}
        terraform-step: 'validate'

    - name: Terraform Plan
      id: plan
      run: terraform plan -detailed-exitcode -no-color || true
      shell: bash

    - name: Post Terraform Plan
      uses: redmagnolia/terraform-custom-actions/commentator@v1
      with:
        github-token: ${{ inputs.github-token }}
        valid-plan: ${{ steps.fmt.outcome == 'success' && steps.init.outcome == 'success' && steps.validate.outcome == 'success' && steps.plan.outcome == 'success' }}
        plan-output: ${{ steps.plan.outputs.stdout }}
        plan-error: ${{ steps.plan.outputs.stderr }}
        terraform-step: 'plan'

    - name: Terraform Plan Error
      if: ${{ steps.plan.outputs.exitcode == '1' }}
      run: exit 1
      shell: bash
