name: 'Terraform Apply'
description: 'Runs terraform apply for a configuration'

runs:
  using: 'composite'

  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.x.x

    - name: Terraform Apply
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        terraform fmt -check
        terraform init
        terraform validate
        terraform apply -auto-approve
      shell: bash
