name: 'Terraform Apply'
description: 'Runs terraform apply for a configuration'

inputs:
  working-directory:
    description: 'The path to run the composite steps'
    required: false
    default: "./"

runs:
  using: 'composite'

  steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.x.x

    - name: Terraform Apply
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        terraform fmt -check
        terraform init
        terraform validate
        terraform apply -auto-approve
      shell: bash
      working-directory: ${{ inputs.working-directory }}
